#!/usr/bin/env node
/**
 * Regenerate src/main/vendor/ml-kem.cjs: ML-KEM-768 (FIPS 203) from
 * @noble/post-quantum, bundled to CommonJS.
 *
 * Why vendored: the package is ESM-only, and the main process, the Electron
 * runtime test and the plain-Node test loader all `require()` — Electron 32's
 * Node cannot require ESM. The file is a verbatim esbuild bundle of the pinned
 * devDependency; regenerate after bumping it:
 *
 *   node tools/vendor-mlkem.cjs
 */
const { buildSync } = require('esbuild');
const { readFileSync, writeFileSync } = require('node:fs');
const { join } = require('node:path');
const { createHash } = require('node:crypto');

const root = join(__dirname, '..');
const pkg = (n) => JSON.parse(readFileSync(join(root, 'node_modules', n, 'package.json'), 'utf8')).version;
const out = join(root, 'src/main/vendor/ml-kem.cjs');
const r = buildSync({
  stdin: { contents: "export { ml_kem768 } from '@noble/post-quantum/ml-kem.js';", resolveDir: root, loader: 'js' },
  bundle: true, platform: 'node', format: 'cjs', target: 'node18', write: false, legalComments: 'inline'
});
const code = r.outputFiles[0].text;
const header = `/* GENERATED by tools/vendor-mlkem.cjs — do not edit.
 * @noble/post-quantum ${pkg('@noble/post-quantum')} (ml_kem768 only), @noble/hashes ${pkg('@noble/hashes')}
 * MIT License, (c) Paul Miller (https://paulmillr.com). sha256(bundle)=${createHash('sha256').update(code).digest('hex')}
 */
`;
writeFileSync(out, header + code);
console.log(`[vendor-mlkem] ${out} (${code.length} bytes)`);
